### ISSUE TITLE
Binance integration

### ISSUE THREAD

**Issue by ghost** [gobeli/pump-and-dump#8] opened 2018-01-10 12:57 UTC
Binance is one of the biggest Crypto exchange, definitely worth some integration

**Comment by gobeli** [comment] 2018-01-10 16:56
Dupe of #7 Since this would be resolved with integrating ccxt

**Closed as completed by gobeli** 2018-01-10 16:56 UTC

**Comment by ghost** [comment] 2018-01-11 07:04
Possible ETA?

**Comment by gobeli** [comment] 2018-01-11 10:26
Hard to say I'm currently in the middle of uni exams, but if you have knowledge in JS I'd be more than happy to accept a PR :)

**Comment by ghost** [comment] 2018-01-11 10:31
Nope, I am using ps/bash/ruby for scripting. JS is totally unknown area for me :(
